# Generated by Django 5.2.8 on 2025-11-20 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outflow',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
